title: Logs
modelClass: OFFLINE\CSP\Models\CSPLog
list: $/offline/csp/models/csplog/columns.yaml
recordUrl: 'offline/csp/csplogs/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
defaultSort: created_at DESC
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
